import React from 'react';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Disclaimer | KnowYourName',
    description: 'Legal disclaimer regarding the accuracy and purpose of Know Your Name analysis.',
};

export default function DisclaimerPage() {
    return (
        <div className="max-w-3xl mx-auto px-4 py-16 text-slate-700 dark:text-slate-300 space-y-8 animate-fade-in-up">
            <header className="border-b border-slate-200 dark:border-slate-800 pb-6 mb-8">
                <h1 className="text-3xl font-bold text-slate-900 dark:text-white mb-2">Disclaimer</h1>
                <p className="text-slate-500 text-sm">Last Updated: October 2023</p>
            </header>

            <section className="space-y-4">
                <h2 className="text-xl font-semibold text-slate-900 dark:text-white">1. Educational & Entertainment Purpose</h2>
                <p>
                    The information provided by Know Your Name ("we," "us," or "our") on knowyourname.co.in (the "Site") is for general educational and entertainment purposes only.
                    All information on the Site is provided in good faith, however, we make no representation or warranty of any kind, express or implied, regarding the accuracy,
                    adequacy, validity, reliability, availability, or completeness of any information on the Site.
                </p>
            </section>

            <section className="space-y-4">
                <h2 className="text-xl font-semibold text-slate-900 dark:text-white">2. Scientific Foundation & Credits</h2>
                <p>
                    The structural analysis and insights provided by our engine are inspired by and built upon established, peer-reviewed research in the fields of quantitative linguistics, phonosemantics, and acoustic physics. We credit the foundational work of researchers such as V.S. Ramachandran & E.M. Hubbard (for the Bouba-Kiki effect), H. Song & N. Schwarz (on typing effort and cognitive fluency), and J. Simner et al. (on grapheme-color synesthesia).
                </p>
                <p>
                    This is <strong>not</strong> an astrology, numerology, or fortune-telling tool. All outputs are data-driven measurements of the acoustic and visual properties of names. However, these correlations represent statistical tendencies in human perception, not deterministic truths about an individual's soul, personality, or destiny.
                </p>
            </section>

            <section className="space-y-4">
                <h2 className="text-xl font-semibold text-slate-900 dark:text-white">3. No Professional Advice</h2>
                <p>
                    The analysis provided by our algorithms is based on linguistics and phonology. It does <strong>not</strong> contain psychological, medical, legal, or financial advice.
                    The structural analysis of a name should not be used as a basis for important life decisions, including but not limited to hiring, naming children, or relationship compatibility.
                </p>
            </section>

            <section className="space-y-4">
                <h2 className="text-xl font-semibold text-slate-900 dark:text-white">4. Advertising & Affiliates</h2>
                <p>
                    The Site may contain advertisements, sponsored content, paid insertions, affiliate links, or other forms of monetization.
                </p>
                <div className="p-4 bg-amber-50 dark:bg-amber-900/20 border-l-4 border-amber-500 text-slate-700 dark:text-slate-300">
                    <strong>Google AdSense Disclosure:</strong> We use Google AdSense to serve ads. These ads are automatically generated by Google and do not necessarily reflect
                    our views or endorsements. We are not responsible for the content of external websites linked via these advertisements.
                </div>
            </section>

            <section className="space-y-4">
                <h2 className="text-xl font-semibold text-slate-900 dark:text-white">5. Limitation of Liability</h2>
                <p>
                    Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of the site or reliance on any
                    information provided on the site. Your use of the site and your reliance on any information on the site is solely at your own risk.
                </p>
            </section>
        </div>
    );
};
